Namespace(N_min=2000, dir='/project2/depablo/walt/michrom/project/chr_05/chr_05_02', down_sampling=48, its=5, jobs=20, mode='contact_diffusion', odir='/project2/depablo/erschultz/michrom/project/chr_05/chr_05_02_copy/contact_diffusion', sparse_format=False, update_mode='eig')
Loaded xyz with shape (252, 3620, 3)
xyz load time: 185.446 s
found 20 total CPUs, 20 available CPUs, using 20
(252, 6554010)
sc_contacts size: 13.2 Gigabytes
Loaded 252 sc contacts
sc load time: 51.853 s
sc_contacts size: 13.2 Gigabytes
Iteration 0
plot time: 48.58 s


Iteration 1
diag time: 11.704 s
distance time: 17.919 s
Using epsilon = 0.223
w [1.         0.06724752 0.04807423 0.04456998 0.04162557]


order corr:  0.85
Using k = 6
update time: 72.067 s
Traceback (most recent call last):
  File "diffusion_analysis.py", line 494, in <module>
    main()
  File "diffusion_analysis.py", line 488, in main
    contact_diffusion()
  File "diffusion_analysis.py", line 394, in contact_diffusion
    plot_contacts(order, sc_contacts, args, odir_i)
  File "diffusion_analysis.py", line 257, in plot_contacts
    filenames = plot_sc_contact_maps_inner(sc_contacts,
  File "/home/erschultz/sequences_to_contact_maps/utils/plotting_utils.py", line 1296, in plot_sc_contact_maps_inner
    with multiprocessing.Pool(jobs) as p:
  File "/home/erschultz/miniconda3/envs/python3.8_pytorch1.8.1_cuda10.2_2/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/erschultz/miniconda3/envs/python3.8_pytorch1.8.1_cuda10.2_2/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/home/erschultz/miniconda3/envs/python3.8_pytorch1.8.1_cuda10.2_2/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/home/erschultz/miniconda3/envs/python3.8_pytorch1.8.1_cuda10.2_2/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/home/erschultz/miniconda3/envs/python3.8_pytorch1.8.1_cuda10.2_2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/erschultz/miniconda3/envs/python3.8_pytorch1.8.1_cuda10.2_2/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/erschultz/miniconda3/envs/python3.8_pytorch1.8.1_cuda10.2_2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/erschultz/miniconda3/envs/python3.8_pytorch1.8.1_cuda10.2_2/lib/python3.8/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
